### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by joshdavidson** [BotLibre/BotLibre#22]
Project is currently missing files needed to build a Docker image

**Comment by jamesssss** [comment]
We have a docker image that we use internally. We are working on publishing this.

**Comment by jamesssss** [comment]
The docker image is now released,

https://github.com/BotLibre/BotLibre/tree/master/botlibre-web/docker

**Comment by jamesssss** [comment]
See, https://www.botlibre.com/forum-post?id=34530981
