### ISSUE TITLE
if i want to use BotLibre,Do i have to register？

### ISSUE THREAD

**Issue by shinemeteor** [BotLibre/BotLibre#40]
As the title

**Comment by jamesssss** [comment]
No. You can check out our source form Git, or download our platform here,
https://www.botlibre.com/download.jsp

We would recommend you register with us to keep up to date on news and patches, we also offer support and services.
You can register here,
https://www.botlibre.com/contact.jsp

**Comment by shinemeteor** [comment]
> No. You can check out our source form Git, or download our platform here,
> https://www.botlibre.com/download.jsp
> 
> We would recommend you register with us to keep up to date on news and patches, we also offer support and services.
> You can register here,
> https://www.botlibre.com/contact.jsp

3q,I have another question，I have a project that uses myql, do I have to install postgresql for integration BotLibre?

**Comment by jamesssss** [comment]
Yes, the Bot Libre platform requires PostgreSQL.
Our platform is somewhat database agnostic, but would require development to get it to work on MySQL, and MySQL has a lot of limitations that PostgreSQL does not.

**Comment by shinemeteor** [comment]
> PostgreSQL

3q
