### ISSUE TITLE
Error deploying war

### ISSUE THREAD

**Issue by igmer** [BotLibre/BotLibre#63]
I'm trying to deploy the project on tomcat server but I'm gettting the error:

     Caused by: java.lang.ClassNotFoundException: org.eclipse.persistence.internal.weaving.PersistenceWeaved

I used the command to build the .war file

       ant -lib ./lib/jpa/eclipselink.jar -lib ./lib/jpa/persistence.jar war

**Comment by jamesssss** [comment]
Make sure you follow the install guide,
https://www.botlibre.com/installation-guide.pdf

https://www.botlibre.com/getting-started-guide.pdf

and add all of the required jars to tomcat/lib from,
https://github.com/BotLibre/BotLibre/tree/master/botlibre-web/lib

**Comment by 1211454975** [comment]
i cannot downlod lib.zip from https://www.botlibre.biz/download/lib.zip

**Comment by 1211454975** [comment]
https://www.botlibre.biz/download/voices52.zip

**Comment by jamesssss** [comment]
This issue has been fixed. Thank you for reporting it.
