### ISSUE TITLE
Is there a working example of swingdroid I can look at?

### ISSUE THREAD

**Issue by DuarteBarbosaPT** [BotLibre/BotLibre#65]
Hi
I'm looking for an example of the swingdroid lib working with a project.
I think that it may be outdated, but that's ok I just wanna see how it works with a basic project.
I tried to do it myself but I couldn't make it work with a simple empty activity in android studio

**Comment by jamesssss** [comment]
It is outdated. But you can see an example here,
https://github.com/BotLibre/BotLibre/tree/master/botlibre-desktop
